"""initial data model

Revision ID: 383c995657f3
Revises:
Create Date: 2026-07-21 11:36:19.178779
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "383c995657f3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "api_usage",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider_request_id", sa.String(length=200), nullable=True),
        sa.Column("usage_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_api_usage_created_at", "api_usage", ["created_at"], unique=False)
    op.create_index(op.f("ix_api_usage_user_id"), "api_usage", ["user_id"], unique=False)
    op.create_table(
        "chatrooms",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chatrooms_expires_at", "chatrooms", ["expires_at"], unique=False)
    op.create_index(op.f("ix_chatrooms_user_id"), "chatrooms", ["user_id"], unique=False)
    op.create_table(
        "collections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_collections_user_name"),
    )
    op.create_index(op.f("ix_collections_user_id"), "collections", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("chatroom_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chatroom_id"], ["chatrooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chatroom_id"), "messages", ["chatroom_id"], unique=False)
    op.create_index("ix_messages_expires_at", "messages", ["expires_at"], unique=False)
    op.create_table(
        "image_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("chatroom_id", sa.String(length=32), nullable=True),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("parent_image_id", sa.String(length=32), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("compiled_prompt", sa.Text(), nullable=True),
        sa.Column("generation_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["chatroom_id"], ["chatrooms.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_image_id"], ["image_records.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_image_records_chatroom_id"), "image_records", ["chatroom_id"], unique=False
    )
    op.create_index("ix_image_records_expires_at", "image_records", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_image_records_message_id"), "image_records", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_image_records_parent_image_id"), "image_records", ["parent_image_id"], unique=False
    )
    op.create_index(op.f("ix_image_records_user_id"), "image_records", ["user_id"], unique=False)
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("request_data", sa.JSON(), nullable=False),
        sa.Column("result_record_id", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["result_record_id"], ["image_records.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_generation_jobs_user_id"), "generation_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "image_assets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("image_record_id", sa.String(length=32), nullable=False),
        sa.Column("asset_type", sa.String(length=30), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("is_saved", sa.Boolean(), nullable=False),
        sa.Column("deletion_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["image_record_id"], ["image_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_record_id", "asset_type", name="uq_image_assets_record_type"),
    )
    op.create_index("ix_image_assets_expires_at", "image_assets", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_image_assets_image_record_id"), "image_assets", ["image_record_id"], unique=False
    )
    op.create_index(
        op.f("ix_image_assets_storage_key"), "image_assets", ["storage_key"], unique=False
    )
    op.create_table(
        "collection_assets",
        sa.Column("collection_id", sa.String(length=32), nullable=False),
        sa.Column("image_asset_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["image_asset_id"], ["image_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("collection_id", "image_asset_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_assets")
    op.drop_index(op.f("ix_image_assets_storage_key"), table_name="image_assets")
    op.drop_index(op.f("ix_image_assets_image_record_id"), table_name="image_assets")
    op.drop_index("ix_image_assets_expires_at", table_name="image_assets")
    op.drop_table("image_assets")
    op.drop_index(op.f("ix_generation_jobs_user_id"), table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_index(op.f("ix_image_records_user_id"), table_name="image_records")
    op.drop_index(op.f("ix_image_records_parent_image_id"), table_name="image_records")
    op.drop_index(op.f("ix_image_records_message_id"), table_name="image_records")
    op.drop_index("ix_image_records_expires_at", table_name="image_records")
    op.drop_index(op.f("ix_image_records_chatroom_id"), table_name="image_records")
    op.drop_table("image_records")
    op.drop_index("ix_messages_expires_at", table_name="messages")
    op.drop_index(op.f("ix_messages_chatroom_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_collections_user_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_chatrooms_user_id"), table_name="chatrooms")
    op.drop_index("ix_chatrooms_expires_at", table_name="chatrooms")
    op.drop_table("chatrooms")
    op.drop_index(op.f("ix_api_usage_user_id"), table_name="api_usage")
    op.drop_index("ix_api_usage_created_at", table_name="api_usage")
    op.drop_table("api_usage")
    op.drop_table("users")
    # ### end Alembic commands ###
